ALTER TABLE venta DROP CONSTRAINT IF EXISTS venta_estado_check;
ALTER TABLE venta ADD CONSTRAINT venta_estado_check
    CHECK (estado IN ('CONFIRMADA', 'ANULACION_SOLICITADA', 'ANULADA', 'PENDIENTE_PAGO', 'CANCELADA_SIN_PAGO'));

COMMENT ON COLUMN venta.estado IS 'CONFIRMADA|ANULACION_SOLICITADA|ANULADA|PENDIENTE_PAGO|CANCELADA_SIN_PAGO. ANULADA implica reversión operativa de stock; no implica reembolso.';
